# LogiSwarm - Geo-Aware Swarm Intelligence for Supply Chains
# Copyright (C) 2025 LogiSwarm Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at) option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Any


def _a(
    region_id: str,
    region_name: str,
    tier: int,
    bbox: tuple[float, float, float, float],
    specialization: str,
    key_locations: list[str],
    poll_interval_seconds: int = 60,
    confidence_threshold: float = 0.75,
    prompt_weights: dict[str, float] | None = None,
    parent_region: str | None = None,
    seasonal_risks: list[str] | None = None,
    trade_lanes: list[str] | None = None,
) -> dict[str, Any]:
    prompt_weights = prompt_weights or {
        "ais_weight": 1.0,
        "weather_weight": 1.0,
        "gdelt_weight": 0.5,
        "carrier_weight": 1.0,
        "port_sensor_weight": 1.0,
    }
    seasonal_risks = seasonal_risks or []
    trade_lanes = trade_lanes or []
    return {
        "region_id": region_id,
        "region_name": region_name,
        "tier": tier,
        "bbox": bbox,
        "parent_region": parent_region,
        "specialization": specialization,
        "key_locations": key_locations,
        "poll_interval_seconds": poll_interval_seconds,
        "confidence_threshold": confidence_threshold,
        "prompt_weights": prompt_weights,
        "seasonal_risks": seasonal_risks,
        "trade_lanes": trade_lanes,
    }


TIER_1_REGIONS: list[dict[str, Any]] = [
    _a("se_asia", "Southeast Asia / Strait of Malacca", 1,
       (92.0, -10.0, 142.0, 25.0), "regional",
       ["Strait of Malacca", "Port of Singapore", "Port Klang", "Tanjung Priok", "Manila"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.5, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 1.2, "port_sensor_weight": 1.3},
       seasonal_risks=["Monsoon season (Jun-Sep)", "Typhoon season (Jul-Nov)"],
       trade_lanes=["Singapore-Shanghai", "Singapore-Suez", "Singapore-Rotterdam"]),
    _a("europe", "Europe Logistics Corridor", 1,
       (-10.0, 35.0, 30.0, 65.0), "regional",
       ["Port of Rotterdam", "Port of Hamburg", "Port of Antwerp", "Bremerhaven", "Felixstowe"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.2, "gdelt_weight": 0.7, "carrier_weight": 1.3, "port_sensor_weight": 1.0},
       seasonal_risks=["North Sea winter storms (Nov-Mar)", "Rhine water level droughts (summer)"],
       trade_lanes=["Rotterdam-Shanghai", "Rotterdam-NY", "Hamburg-Baltic"]),
    _a("gulf_suez", "Gulf / Suez Risk Corridor", 1,
       (32.0, 10.0, 60.0, 30.0), "regional",
       ["Suez Canal", "Bab-el-Mandeb Strait", "Strait of Hormuz", "Jebel Ali Port", "Jeddah"],
       poll_interval_seconds=45, confidence_threshold=0.60,
       prompt_weights={"ais_weight": 1.3, "weather_weight": 0.7, "gdelt_weight": 2.0, "carrier_weight": 1.0, "port_sensor_weight": 1.0},
       seasonal_risks=["Houthi attacks (persistent)", "Suez congestion", "Sand storms (spring)"],
       trade_lanes=["Suez-Rotterdam", "Suez-Singapore", "Hormuz-India"]),
    _a("north_america", "North America Intermodal Network", 1,
       (-130.0, 20.0, -60.0, 55.0), "regional",
       ["Port of LA/Long Beach", "Port of New York/New Jersey", "Port of Savannah", "Chicago Rail Hub", "Port of Vancouver"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 0.8, "gdelt_weight": 0.5, "carrier_weight": 1.5, "port_sensor_weight": 1.2},
       seasonal_risks=["Hurricane season (Jun-Nov)", "Winter storms (Dec-Mar)", "ILWU labor negotiations"],
       trade_lanes=["LA-Shanghai", "NY-Rotterdam", "LA-Chicago rail"]),
    _a("china_ea", "China / East Asia Export Corridor", 1,
       (100.0, 18.0, 145.0, 45.0), "regional",
       ["Port of Shanghai", "Port of Ningbo-Zhoushan", "Port of Busan", "Port of Shenzhen", "Port of Hong Kong"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 0.8, "gdelt_weight": 0.7, "carrier_weight": 1.3, "port_sensor_weight": 1.4},
       seasonal_risks=["Typhoon season (Jul-Oct)", "Chinese New Year shutdown", "Golden Week (Oct)"],
       trade_lanes=["Shanghai-LA", "Shanghai-Rotterdam", "Busan-Seattle"]),
    _a("south_asia", "South Asia / Indian Ocean", 1,
       (68.0, -5.0, 95.0, 25.0), "regional",
       ["Port of Mumbai (Nhava Sheva)", "Port of Colombo", "Port of Chennai", "Port of Mundra", "Port of Chittagong"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.5, "gdelt_weight": 0.5, "carrier_weight": 1.0, "port_sensor_weight": 0.8},
       seasonal_risks=["Monsoon cyclone season (Apr-Dec)", "Bay of Bengal cyclones"],
       trade_lanes=["Mumbai-Singapore", "Colombo-Suez", "Chennai-Bangkok"]),
    _a("latin_america", "Latin America", 1,
       (-85.0, -60.0, -30.0, 15.0), "regional",
       ["Panama Canal", "Port of Santos", "Port of Callao", "Port of Buenos Aires", "Port of Cartagena"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 0.8, "weather_weight": 1.2, "gdelt_weight": 0.6, "carrier_weight": 0.8, "port_sensor_weight": 0.7},
       seasonal_risks=["Panama Canal drought restrictions", "El Nino/La Nina"],
       trade_lanes=["Panama-LA", "Santos-Rotterdam", "Cartagena-Miami"]),
    _a("africa", "Africa / Cape of Good Hope", 1,
       (-10.0, -40.0, 55.0, 5.0), "regional",
       ["Port of Cape Town", "Port of Durban", "Port of Lagos", "Port of Mombasa", "Port of Dar es Salaam"],
       poll_interval_seconds=60, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 0.7, "weather_weight": 1.3, "gdelt_weight": 0.5, "carrier_weight": 0.7, "port_sensor_weight": 0.6},
       seasonal_risks=["Cape of Good Hope weather (Jun-Aug)", "Mozambique Channel cyclones"],
       trade_lanes=["Cape Town-Rotterdam", "Lagos-Rotterdam", "Mombasa-Dubai"]),
]

TIER_2_REGIONS: list[dict[str, Any]] = [
    _a("choke_malacca", "Malacca Strait Zone", 2, (98.0, -2.0, 105.0, 8.0), "chokepoint",
       ["Strait of Malacca", "Strait of Singapore", "Phillip Channel"],
       parent_region="se_asia", poll_interval_seconds=120, confidence_threshold=0.70,
       prompt_weights={"ais_weight": 2.0, "weather_weight": 1.2, "gdelt_weight": 0.5, "carrier_weight": 1.5, "port_sensor_weight": 1.8},
       seasonal_risks=["Monsoon traffic disruption", "Piracy risk"],
       trade_lanes=["Singapore-Shanghai", "Singapore-Suez"]),
    _a("choke_suez", "Suez Canal Zone", 2, (31.0, 28.0, 34.0, 31.5), "chokepoint",
       ["Suez Canal", "Port Said", "Suez Port"],
       parent_region="gulf_suez", poll_interval_seconds=90, confidence_threshold=0.65,
       prompt_weights={"ais_weight": 2.0, "weather_weight": 0.8, "gdelt_weight": 2.0, "carrier_weight": 1.2, "port_sensor_weight": 1.5},
       seasonal_risks=["Suez congestion", "Canal closure risk", "Houthi attacks"],
       trade_lanes=["Suez-Rotterdam", "Suez-Singapore"]),
    _a("choke_hormuz", "Strait of Hormuz", 2, (55.0, 25.0, 57.5, 27.0), "chokepoint",
       ["Strait of Hormuz", "Port of Fujairah", "Khawr Fakkan"],
       parent_region="gulf_suez", poll_interval_seconds=90, confidence_threshold=0.65,
       prompt_weights={"ais_weight": 2.0, "weather_weight": 0.7, "gdelt_weight": 2.5, "carrier_weight": 1.0, "port_sensor_weight": 1.2},
       seasonal_risks=["Geopolitical tension", "Iran sanctions risk"],
       trade_lanes=["Hormuz-India", "Hormuz-Rotterdam"]),
    _a("choke_bab_el_mandeb", "Bab-el-Mandeb Strait", 2, (42.0, 11.5, 45.0, 14.5), "chokepoint",
       ["Bab-el-Mandeb", "Djibouti Port", "Aden Port"],
       parent_region="gulf_suez", poll_interval_seconds=90, confidence_threshold=0.65,
       prompt_weights={"ais_weight": 1.8, "weather_weight": 0.8, "gdelt_weight": 2.0, "carrier_weight": 1.0, "port_sensor_weight": 1.0},
       seasonal_risks=["Houthi attacks", "Piracy risk"],
       trade_lanes=["Suez-Indian Ocean", "Red Sea transit"]),
    _a("choke_gibraltar", "Strait of Gibraltar", 2, (-6.5, 35.0, -4.5, 36.5), "chokepoint",
       ["Strait of Gibraltar", "Port of Algeciras", "Port of Tanger Med"],
       parent_region="europe", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.5, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 1.2, "port_sensor_weight": 1.0},
       seasonal_risks=["Levante wind disruptions"],
       trade_lanes=["Med-Atlantic", "Algeciras-Rotterdam"]),
    _a("choke_panama", "Panama Canal Zone", 2, (-80.0, 8.5, -78.0, 10.0), "chokepoint",
       ["Panama Canal", "Port of Balboa", "Port of Colon"],
       parent_region="latin_america", poll_interval_seconds=120, confidence_threshold=0.70,
       prompt_weights={"ais_weight": 1.5, "weather_weight": 1.5, "gdelt_weight": 0.5, "carrier_weight": 1.2, "port_sensor_weight": 1.2},
       seasonal_risks=["Canal drought restrictions", "El Nino draft limits"],
       trade_lanes=["Panama-LA", "Panama-NY"]),
    _a("choke_bosporus", "Turkish Straits", 2, (28.5, 40.5, 30.0, 42.0), "chokepoint",
       ["Bosporus Strait", "Dardanelles", "Port of Istanbul"],
       parent_region="europe", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.3, "weather_weight": 1.0, "gdelt_weight": 1.0, "carrier_weight": 0.8, "port_sensor_weight": 1.0},
       seasonal_risks=["Bosporus congestion", "Turkish policy changes"],
       trade_lanes=["Black Sea-Mediterranean"]),
    _a("choke_lombok", "Lombok Strait", 2, (115.0, -9.0, 117.0, -7.5), "chokepoint",
       ["Lombok Strait", "Makassar Strait"],
       parent_region="se_asia", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.0, "gdelt_weight": 0.3, "carrier_weight": 0.8, "port_sensor_weight": 0.5},
       seasonal_risks=["Alternate route when Malacca disrupted"],
       trade_lanes=["Lombok alternate route"]),
    _a("cluster_rotterdam", "Rotterdam-Europe Cluster", 2, (3.0, 51.0, 5.5, 52.5), "seaport_cluster",
       ["Port of Rotterdam", "Port of Antwerp", "Port of Hamburg", "Port of Bremerhaven", "Port of Felixstowe"],
       parent_region="europe", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 1.5, "port_sensor_weight": 1.3},
       seasonal_risks=["North Sea storms", "Dock strikes"],
       trade_lanes=["Rotterdam-Shanghai", "Rotterdam-NY", "Hamburg-Baltic"]),
    _a("cluster_shanghai", "Shanghai-Yangtze Cluster", 2, (120.0, 29.0, 123.0, 32.5), "seaport_cluster",
       ["Port of Shanghai", "Port of Ningbo-Zhoushan", "Yangshan Deep Water"],
       parent_region="china_ea", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.5, "weather_weight": 0.8, "gdelt_weight": 0.5, "carrier_weight": 1.5, "port_sensor_weight": 1.5},
       seasonal_risks=["Typhoon season (Jul-Oct)", "Yangtze flooding"],
       trade_lanes=["Shanghai-LA", "Shanghai-Rotterdam"]),
    _a("cluster_la_longbeach", "LA-Long Beach Cluster", 2, (-118.5, 33.0, -117.5, 34.0), "seaport_cluster",
       ["Port of Los Angeles", "Port of Long Beach"],
       parent_region="north_america", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.3, "weather_weight": 0.7, "gdelt_weight": 0.5, "carrier_weight": 1.8, "port_sensor_weight": 1.5},
       seasonal_risks=["ILWU labor disputes", "Holiday congestion"],
       trade_lanes=["LA-Shanghai", "LA-Tokyo"]),
    _a("cluster_singapore", "Singapore Hub", 2, (103.5, 1.0, 104.5, 1.8), "seaport_cluster",
       ["Port of Singapore", "TSA Container Terminal", "Jurong Port"],
       parent_region="se_asia", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.8, "weather_weight": 0.8, "gdelt_weight": 0.3, "carrier_weight": 1.5, "port_sensor_weight": 1.5},
       seasonal_risks=["Smoke haze from Indonesia", "Monsoon congestion"],
       trade_lanes=["Singapore-Suez", "Singapore-Shanghai"]),
    _a("cluster_dubai", "Dubai-Gulf Hub", 2, (54.5, 24.5, 56.0, 26.0), "seaport_cluster",
       ["Jebel Ali Port", "Port Rashid", "DP World Hub"],
       parent_region="gulf_suez", poll_interval_seconds=120, confidence_threshold=0.70,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 0.6, "gdelt_weight": 1.5, "carrier_weight": 1.3, "port_sensor_weight": 1.0},
       seasonal_risks=["Extreme heat (Jun-Sep)", "Regional tensions"],
       trade_lanes=["Dubai-India", "Dubai-Europe"]),
    _a("cluster_mumbai", "Mumbai-India Cluster", 2, (72.0, 18.0, 73.5, 19.5), "seaport_cluster",
       ["Nhava Sheva (JNPT)", "Port of Mumbai", "Mumbai Port Trust"],
       parent_region="south_asia", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.5, "gdelt_weight": 0.5, "carrier_weight": 1.0, "port_sensor_weight": 0.8},
       seasonal_risks=["Monsoon (Jun-Sep)", "Cyclone season"],
       trade_lanes=["Mumbai-Singapore", "Mumbai-Suez"]),
    _a("cluster_santos", "Santos-South America Cluster", 2, (-47.0, -24.0, -45.5, -23.0), "seaport_cluster",
       ["Port of Santos", "Port of Paranagua", "Port of Rio Grande"],
       parent_region="latin_america", poll_interval_seconds=120, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.8, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 0.8, "port_sensor_weight": 0.7},
       seasonal_risks=["Brazilian rainy season", "Soy export season peaks"],
       trade_lanes=["Santos-Rotterdam", "Santos-Shanghai"]),
    _a("cluster_cape_town", "Cape Town-Cape Route", 2, (17.5, -35.0, 19.5, -33.5), "seaport_cluster",
       ["Port of Cape Town", "Cape of Good Hope waypoint"],
       parent_region="africa", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.5, "gdelt_weight": 0.3, "carrier_weight": 0.7, "port_sensor_weight": 0.5},
       seasonal_risks=["Cape storms (Jun-Aug)", "Suez alternative route"],
       trade_lanes=["Cape Town-Rotterdam"]),
    _a("cluster_busan", "Busan-Northeast Asia Hub", 2, (128.5, 34.5, 130.0, 36.0), "seaport_cluster",
       ["Port of Busan", "Port of Incheon"],
       parent_region="china_ea", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 0.8, "gdelt_weight": 0.5, "carrier_weight": 1.2, "port_sensor_weight": 1.2},
       seasonal_risks=["Typhoon season (Jul-Sep)", "Korean Peninsula tensions"],
       trade_lanes=["Busan-LA", "Busan-Rotterdam"]),
    _a("cluster_ny_nj", "New York-New Jersey Hub", 2, (-74.5, 40.0, -73.5, 41.0), "seaport_cluster",
       ["Port of NY/NJ", "Port Newark", "Elizabeth-Port Authority"],
       parent_region="north_america", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 1.5, "port_sensor_weight": 1.3},
       seasonal_risks=["Nor'easters (Dec-Mar)", "Hurricane season"],
       trade_lanes=["NY-Rotterdam", "NY-Shanghai"]),
    _a("cluster_savannah", "Savannah-Southeast US Hub", 2, (-81.2, 32.0, -80.5, 32.3), "seaport_cluster",
       ["Port of Savannah", "Port of Charleston"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 1.0, "weather_weight": 1.0, "gdelt_weight": 0.3, "carrier_weight": 1.3, "port_sensor_weight": 1.0},
       seasonal_risks=["Hurricane season (Jun-Nov)"],
       trade_lanes=["Savannah-Rotterdam", "Savannah-Shanghai"]),
    _a("cluster_colombo", "Colombo-Indian Ocean Hub", 2, (79.5, 6.5, 80.0, 7.5), "seaport_cluster",
       ["Port of Colombo", "Colombo South Harbour"],
       parent_region="south_asia", poll_interval_seconds=120, confidence_threshold=0.75,
       prompt_weights={"ais_weight": 1.2, "weather_weight": 1.0, "gdelt_weight": 0.3, "carrier_weight": 1.3, "port_sensor_weight": 1.0},
       seasonal_risks=["Monsoon disruptions"],
       trade_lanes=["Colombo-Singapore", "Colombo-Suez"]),
    _a("cluster_callao", "Callao-Pacific South America", 2, (-77.2, -12.3, -76.8, -11.8), "seaport_cluster",
       ["Port of Callao"],
       parent_region="latin_america", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.7, "weather_weight": 1.0, "gdelt_weight": 0.4, "carrier_weight": 0.7, "port_sensor_weight": 0.5},
       seasonal_risks=["El Nino flooding"],
       trade_lanes=["Callao-Shanghai", "Callao-LA"]),
    _a("cluster_mombasa", "Mombasa-East Africa Hub", 2, (39.5, -4.2, 40.0, -3.8), "seaport_cluster",
       ["Port of Mombasa"],
       parent_region="africa", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.7, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 0.6, "port_sensor_weight": 0.5},
       seasonal_risks=["Political instability", "Monsoon winds"],
       trade_lanes=["Mombasa-Dubai", "Mombasa-India"]),
    _a("cluster_lagos", "Lagos-West Africa Hub", 2, (2.5, 6.0, 4.0, 6.8), "seaport_cluster",
       ["Port of Lagos (Apapa)", "Lekki Deep Sea Port"],
       parent_region="africa", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.6, "weather_weight": 0.8, "gdelt_weight": 0.6, "carrier_weight": 0.6, "port_sensor_weight": 0.4},
       seasonal_risks=["Port congestion", "Security concerns"],
       trade_lanes=["Lagos-Rotterdam", "Lagos-Shanghai"]),
    _a("hub_memphis", "Memphis Air Cargo Hub", 2, (-90.0, 35.0, -89.8, 35.2), "air_hub",
       ["Memphis International (FedEx)", "Memphis Cargo Hub"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.3, "weather_weight": 1.5, "gdelt_weight": 0.2, "carrier_weight": 2.0, "port_sensor_weight": 0.3},
       seasonal_risks=["Winter storms", "Peak season congestion"],
       trade_lanes=["Memphis-National distribution"]),
    _a("hub_louisville", "Louisville Air Cargo Hub", 2, (-85.8, 38.0, -85.5, 38.3), "air_hub",
       ["Louisville International (UPS Worldport)"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.3, "weather_weight": 1.2, "gdelt_weight": 0.2, "carrier_weight": 2.0, "port_sensor_weight": 0.3},
       seasonal_risks=["Winter storms", "Peak season"],
       trade_lanes=["UPS National distribution"]),
    _a("hub_shanghai_pudong", "Shanghai Pudong Air Cargo", 2, (121.5, 31.1, 121.9, 31.5), "air_hub",
       ["Shanghai Pudong International Cargo"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.3, "weather_weight": 0.8, "gdelt_weight": 0.5, "carrier_weight": 1.8, "port_sensor_weight": 0.5},
       seasonal_risks=["Typhoon disruptions"],
       trade_lanes=["Pudong-Frankfurt", "Pudong-LA"]),
    _a("hub_frankfurt", "Frankfurt Air Cargo Hub", 2, (8.5, 50.0, 8.8, 50.2), "air_hub",
       ["Frankfurt Airport Cargo"],
       parent_region="europe", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.3, "weather_weight": 1.0, "gdelt_weight": 0.3, "carrier_weight": 1.8, "port_sensor_weight": 0.4},
       seasonal_risks=["Winter fog", "ATC strikes"],
       trade_lanes=["Frankfurt-Shanghai", "Frankfurt-NY"]),
    _a("hub_dubai_air", "Dubai Air Cargo Hub", 2, (55.3, 25.1, 55.6, 25.3), "air_hub",
       ["Dubai International Cargo", "Al Maktoum International"],
       parent_region="gulf_suez", poll_interval_seconds=180, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.3, "weather_weight": 0.5, "gdelt_weight": 0.8, "carrier_weight": 1.8, "port_sensor_weight": 0.4},
       seasonal_risks=["Extreme heat operational limits"],
       trade_lanes=["Dubai-London", "Dubai-Singapore"]),
    _a("rail_transsiberian", "Trans-Siberian Rail Corridor", 2, (40.0, 55.0, 140.0, 60.0), "rail_hub",
       ["Moscow Terminal", "Yekaterinburg Hub", "Vladivostok Port"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.2, "weather_weight": 1.5, "gdelt_weight": 0.7, "carrier_weight": 0.5, "port_sensor_weight": 0.3},
       seasonal_risks=["Winter freeze (Nov-Mar)", "Border delays"],
       trade_lanes=["China-Europe rail"]),
    _a("rail_eurasian_land_bridge", "Eurasian Land Bridge", 2, (75.0, 40.0, 120.0, 50.0), "rail_hub",
       ["Khorgos Gateway", "Xi'an Freight Hub", "Chongqing Rail Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.80,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.5, "carrier_weight": 0.5, "port_sensor_weight": 0.3},
       seasonal_risks=["Winter disruptions", "Customs delays"],
       trade_lanes=["China-Europe rail"]),
]

TIER_3_REGIONS: list[dict[str, Any]] = [
    _a("port_shanghai", "Port of Shanghai", 3, (121.3, 30.9, 122.0, 31.7), "seaport",
       ["Yangshan Deep Water", "Waigaoqiao Phase IV"],
       parent_region="cluster_shanghai", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Shanghai-LA", "Shanghai-Rotterdam", "Shanghai-Singapore"]),
    _a("port_ningbo", "Port of Ningbo-Zhoushan", 3, (121.5, 29.7, 122.3, 30.2), "seaport",
       ["Ningbo Container Terminal", "Zhoushan Oil Terminal"],
       parent_region="cluster_shanghai", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Ningbo-LA", "Ningbo-Rotterdam"]),
    _a("port_singapore", "Port of Singapore", 3, (103.6, 1.1, 104.1, 1.5), "seaport",
       ["TSA Container Terminal", "Jurong Island Terminal", "Pasir Panjang"],
       parent_region="cluster_singapore", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Singapore-Suez", "Singapore-Shanghai", "Singapore-Rotterdam"]),
    _a("port_rotterdam", "Port of Rotterdam", 3, (3.9, 51.7, 4.5, 52.1), "seaport",
       ["Euromax Terminal", "Maasvlakte II", "RWG Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Rotterdam-Shanghai", "Rotterdam-NY"]),
    _a("port_hamburg", "Port of Hamburg", 3, (9.7, 53.4, 10.2, 53.7), "seaport",
       ["HHLA Container Terminal", "Eurogate Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Hamburg-Shanghai", "Hamburg-Baltic"]),
    _a("port_antwerp", "Port of Antwerp", 3, (4.2, 51.1, 4.5, 51.4), "seaport",
       ["Antwerp Gateway Terminal", "MSC Home Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Antwerp-Shanghai"]),
    _a("port_la", "Port of Los Angeles", 3, (-118.3, 33.7, -118.1, 33.9), "seaport",
       ["TraPac Terminal", "APM Terminal Pier 400"],
       parent_region="cluster_la_longbeach", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["LA-Shanghai", "LA-Tokyo"]),
    _a("port_longbeach", "Port of Long Beach", 3, (-118.2, 33.7, -118.1, 33.8), "seaport",
       ["Long Beach Container Terminal", "SSA Terminal"],
       parent_region="cluster_la_longbeach", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Long Beach-Shanghai"]),
    _a("port_busan", "Port of Busan", 3, (128.9, 35.0, 129.2, 35.2), "seaport",
       ["Busan New Port", "Jae-gang Terminal"],
       parent_region="cluster_busan", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Busan-LA", "Busan-Rotterdam"]),
    _a("port_jebel_ali", "Jebel Ali Port", 3, (55.0, 24.9, 55.2, 25.1), "seaport",
       ["Jebel Ali Container Terminal 1-4"],
       parent_region="cluster_dubai", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Jebel Ali-India", "Jebel Ali-Europe"]),
    _a("port_nhava_sheva", "Nhava Sheva (JNPT)", 3, (72.9, 18.9, 73.1, 19.1), "seaport",
       ["JNPT Container Terminal", "NSICT Terminal"],
       parent_region="cluster_mumbai", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["JNPT-Singapore", "JNPT-Suez"]),
    _a("port_colombo", "Port of Colombo", 3, (79.8, 6.9, 79.9, 7.0), "seaport",
       ["Colombo International Container Terminal", "South Harbour"],
       parent_region="cluster_colombo", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Colombo-Singapore", "Colombo-Suez"]),
    _a("port_panama", "Panama Canal", 3, (-79.5, 8.9, -79.4, 9.1), "seaport",
       ["Panama Canal Locks", "Balboa Container Terminal"],
       parent_region="choke_panama", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Panama-LA", "Panama-NY"]),
    _a("port_cape_town", "Port of Cape Town", 3, (18.3, -34.0, 18.5, -33.8), "seaport",
       ["Cape Town Container Terminal"],
       parent_region="cluster_cape_town", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Cape Town-Rotterdam"]),
    _a("port_santos", "Port of Santos", 3, (-46.4, -24.0, -46.1, -23.9), "seaport",
       ["Santos Container Terminal", "Brazport Terminal"],
       parent_region="cluster_santos", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Santos-Rotterdam", "Santos-Shanghai"]),
    _a("port_hong_kong", "Port of Hong Kong", 3, (113.9, 22.2, 114.4, 22.5), "seaport",
       ["Kwai Tsing Container Terminals", "Hong Kong International Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["HK-LA", "HK-Rotterdam"]),
    _a("port_shenzhen", "Port of Shenzhen", 3, (113.8, 22.4, 114.6, 22.8), "seaport",
       ["Yantian International Container Terminal", "Chiwan Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Shenzhen-LA", "Shenzhen-Rotterdam"]),
    _a("port_qingdao", "Port of Qingdao", 3, (120.2, 36.0, 120.6, 36.3), "seaport",
       ["Qingdao Qianwan Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Qingdao-LA", "Qingdao-SE Asia"]),
    _a("port_guangzhou", "Port of Guangzhou (Nansha)", 3, (113.4, 22.5, 113.8, 23.0), "seaport",
       ["Nansha Terminal", "Huangpu Port"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Guangzhou-SE Asia", "Guangzhou-Europe"]),
    _a("port_tianjin", "Port of Tianjin", 3, (117.6, 38.9, 118.1, 39.2), "seaport",
       ["Tianjin Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Tianjin-LA", "Tianjin-SE Asia"]),
    _a("port_kaohsiung", "Port of Kaohsiung", 3, (120.2, 22.5, 120.4, 22.7), "seaport",
       ["Kaohsiung Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Kaohsiung-LA", "Kaohsiung-SE Asia"]),
    _a("port_ny_nj", "Port of New York/New Jersey", 3, (-74.2, 40.5, -73.7, 40.8), "seaport",
       ["APM Terminal Elizabeth", "Port Newark Container Terminal"],
       parent_region="cluster_ny_nj", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["NY-Rotterdam", "NY-Shanghai"]),
    _a("port_savannah", "Port of Savannah", 3, (-81.1, 32.1, (-81.0), 32.2), "seaport",
       ["Garden City Terminal"],
       parent_region="cluster_savannah", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Savannah-Rotterdam", "Savannah-Shanghai"]),
    _a("port_anchorage_ak", "Port of Anchorage", 3, (-150.0, 61.1, -149.8, 61.3), "seaport",
       ["Anchorage Port", "Alaska Maritime Highway"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Anchorage-Seattle", "Anchorage-Asia"]),
    _a("port_seattle_tacoma", "Port of Seattle-Tacoma", 3, (-122.5, 47.2, (-122.2), 47.4), "seaport",
       ["Terminal 46 Seattle", "Tacoma Washington United Terminal"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Seattle-Shanghai", "Seattle-Tokyo"]),
    _a("port_melbourne", "Port of Melbourne", 3, (144.8, -37.9, 145.1, -37.7), "seaport",
       ["Melbourne Container Terminal"],
       parent_region="se_asia", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Melbourne-Singapore"]),
    _a("port_syd_port", "Port of Sydney", 3, (151.1, -34.0, 151.3, -33.8), "seaport",
       ["Sydney Container Terminal"],
       parent_region="se_asia", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Sydney-Singapore"]),
    _a("port_lagos", "Port of Lagos (Apapa)", 3, (3.3, 6.4, 3.5, 6.6), "seaport",
       ["Apapa Container Terminal", "Tin Can Island Port"],
       parent_region="cluster_lagos", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Lagos-Rotterdam", "Lagos-Shanghai"]),
    _a("port_mombasa", "Port of Mombasa", 3, (39.6, -4.1, 39.7, -3.9), "seaport",
       ["Mombasa Container Terminal"],
       parent_region="cluster_mombasa", poll_interval_seconds=300, confidence_threshold=0.80,
       trade_lanes=["Mombasa-Dubai", "Mombasa-India"]),
    _a("port_durban", "Port of Durban", 3, (30.9, -30.0, 31.1, -29.8), "seaport",
       ["Durban Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.80,
       trade_lanes=["Durban-Shanghai", "Durban-Rotterdam"]),
    _a("port_callao", "Port of Callao", 3, (-77.15, -12.1, (-77.0), -11.95), "seaport",
       ["Callao Container Terminal"],
       parent_region="cluster_callao", poll_interval_seconds=300, confidence_threshold=0.80,
       trade_lanes=["Callao-Shanghai", "Callao-LA"]),
    _a("port_cartagena", "Port of Cartagena", 3, (-75.6, 10.3, -75.5, 10.5), "seaport",
       ["Cartagena Container Terminal", "SPRC Terminal"],
       parent_region="choke_panama", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Cartagena-Miami", "Cartagena-Rotterdam"]),
    _a("port_tanger_med", "Tanger Med", 3, (-5.6, 35.7, -5.4, 35.9), "seaport",
       ["Tanger Med Container Terminal"],
       parent_region="choke_gibraltar", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Tanger Med-Rotterdam", "Tanger Med-NY"]),
    _a("port_djibouti", "Port of Djibouti", 3, (43.1, 11.5, 43.2, 11.7), "seaport",
       ["Djibouti Container Terminal", "Doraleh Container Terminal"],
       parent_region="choke_bab_el_mandeb", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Djibouti-Suez", "Djibouti-Asia"]),
    _a("port_piraeus", "Port of Piraeus", 3, (23.5, 37.9, 23.7, 38.0), "seaport",
       ["Piraeus Container Terminal"],
       parent_region="europe", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Piraeus-Shanghai", "Piraeus-Rotterdam"]),
    _a("port_klaipeda", "Port of Klaipeda", 3, (21.0, 55.6, 21.3, 55.8), "seaport",
       ["Klaipeda Container Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Klaipeda-Rotterdam", "Klaipeda-Asia"]),
    _a("port_fujairah", "Port of Fujairah", 3, (56.3, 25.1, 56.4, 25.2), "seaport",
       ["Fujairah Oil Terminal", "Fujairah Container Terminal"],
       parent_region="choke_hormuz", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Fujairah-India", "Fujairah-Asia"]),
    _a("air_memphis", "Memphis International (FedEx)", 3, (-90.0, 35.0, (-89.8), 35.2), "airport",
       ["FedEx Superhub", "Memphis sorting facility"],
       parent_region="hub_memphis", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.5, "gdelt_weight": 0.1, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Express distribution"]),
    _a("air_louisville", "Louisville Worldport (UPS)", 3, (-85.8, 38.0, (-85.5), 38.3), "airport",
       ["UPS Worldport Hub"],
       parent_region="hub_louisville", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.5, "gdelt_weight": 0.1, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Express distribution"]),
    _a("air_frankfurt", "Frankfurt Cargo Hub", 3, (8.5, 50.0, 8.8, 50.2), "airport",
       ["Frankfurt Cargo Center"],
       parent_region="hub_frankfurt", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.2, "gdelt_weight": 0.2, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Frankfurt-Shanghai", "Frankfurt-NY"]),
    _a("air_pudong", "Shanghai Pudong Cargo", 3, (121.7, 31.1, 121.9, 31.4), "airport",
       ["Pudong Cargo Terminal"],
       parent_region="hub_shanghai_pudong", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 0.8, "gdelt_weight": 0.3, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Pudong-Frankfurt", "Pudong-LA"]),
    _a("air_dubai", "Dubai International Cargo", 3, (55.3, 25.1, 55.6, 25.3), "airport",
       ["Dubai Cargo Village", "Al Maktoum Cargo"],
       parent_region="hub_dubai_air", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 0.5, "gdelt_weight": 0.5, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Dubai-London", "Dubai-Sydney"]),
    _a("air_anchorage", "Ted Stevens Anchorage International", 3, (-150.0, 61.1, (-149.8), 61.3), "airport",
       ["Anchorage Cargo Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 2.0, "gdelt_weight": 0.1, "carrier_weight": 2.0, "port_sensor_weight": 0.2},
       trade_lanes=["Anchorage-Asia cargo hub"]),
    _a("air_luxembourg", "Luxembourg Cargo Hub", 3, (6.1, 49.6, 6.3, 49.7), "airport",
       ["Cargolux Hub"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.2, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Luxembourg-Asia", "Luxembourg-Americas"]),
    _a("air_leipzig", "Leipzig/Halle Cargo Hub", 3, (12.2, 51.4, 12.5, 51.5), "airport",
       ["DHL Hub Leipzig"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.2, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["DHL Express Distribution"]),
    _a("air_louisville_intl", "Louisville International Cargo", 3, (-85.7, 38.1, (-85.6), 38.3), "airport",
       ["UPS Worldport"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.5, "gdelt_weight": 0.1, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["UPS domestic hub"]),
    _a("air_incheon", "Incheon International Cargo", 3, (126.4, 37.4, 126.5, 37.5), "airport",
       ["Incheon Cargo Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 0.8, "gdelt_weight": 0.3, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Incheon-LA", "Incheon-Europe"]),
    _a("air_narita", "Narita International Cargo", 3, (140.3, 35.7, 140.5, 35.9), "airport",
       ["Narita Cargo Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.2, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["Narita-LA", "Narita-Europe"]),
    _a("air_heathrow", "Heathrow Cargo Hub", 3, (-0.5, 51.5, (-0.4), 51.6), "airport",
       ["Heathrow World Cargo Centre"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.2, "gdelt_weight": 0.2, "carrier_weight": 2.5, "port_sensor_weight": 0.2},
       trade_lanes=["London-Asia", "London-Americas"]),
    _a("rail_chicago", "Chicago Intermodal Hub", 3, (-87.9, 41.6, (-87.5), 42.1), "rail_hub",
       ["BNSF Logistic Center Chicago", "UP Global III Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.2, "gdelt_weight": 0.2, "carrier_weight": 1.5, "port_sensor_weight": 0.5},
       trade_lanes=["Chicago-LA rail", "Chicago-NY rail"]),
    _a("rail_dallas", "Dallas Intermodal Hub", 3, (-97.0, 32.7, (-96.8), 32.9), "rail_hub",
       ["BNSF Alliance Terminal", "UP Dallas Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.2, "carrier_weight": 1.2, "port_sensor_weight": 0.4},
       trade_lanes=["Houston-Dallas rail", "Midwest distribution"]),
    _a("rail_duisburg", "Duisburg Rail Terminal", 3, (6.7, 51.4, 6.8, 51.5), "rail_hub",
       ["Duisburg Intermodal Terminal", "DUSS Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.2, "carrier_weight": 1.0, "port_sensor_weight": 0.5},
       trade_lanes=["China-Europe rail terminal"]),
    _a("rail_mumbai_delhi", "Mumbai-Delhi Rail Corridor", 3, (72.8, 19.0, 77.2, 28.6), "rail_hub",
       ["JNPT-Delhi ICD", "Delhi Dry Port"],
       parent_region="south_asia", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.1, "weather_weight": 1.0, "gdelt_weight": 0.3, "carrier_weight": 0.8, "port_sensor_weight": 0.4},
       trade_lanes=["Mumbai-Delhi rail", "ICD Dadri"]),
    _a("dry_port_khorgos", "Khorgos Gateway Dry Port", 3, (80.3, 44.0, 80.5, 44.2), "dry_port",
       ["Khorgos Gateway SEZ", "ICD Khorgos"],
       parent_region="rail_eurasian_land_bridge", poll_interval_seconds=300, confidence_threshold=0.85,
       prompt_weights={"ais_weight": 0.0, "weather_weight": 1.2, "gdelt_weight": 0.5, "carrier_weight": 0.5, "port_sensor_weight": 0.3},
       trade_lanes=["China-Europe rail"]),
    _a("dry_port_dadri", "ICD Dadri (Delhi)", 3, (77.5, 28.5, 77.7, 28.6), "dry_port",
       ["ICD Dadri Container Terminal"],
       parent_region="rail_mumbai_delhi", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Mumbai-Delhi inland"]),
    _a("dry_port_memphis", "Memphis Intermodal Terminal", 3, (-90.0, 35.0, (-89.8), 35.2), "dry_port",
       ["Memphis Intermodal Facility", "BNSF Memphis Terminal"],
       parent_region="hub_memphis", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["National rail distribution"]),
    _a("port_gdansk", "Port of Gdansk", 3, (18.5, 54.3, 18.8, 54.5), "seaport",
       ["Deepwater Container Terminal Gdansk"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Gdansk-Asia", "Gdansk-Rotterdam"]),
    _a("port_bremerhaven", "Port of Bremerhaven", 3, (8.5, 53.5, 8.7, 53.6), "seaport",
       ["NTB North Terminal", "Bremerhaven Container Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Bremerhaven-Asia", "Bremerhaven-NY"]),
    _a("port_felixstowe", "Port of Felixstowe", 3, (1.2, 51.9, 1.4, 52.0), "seaport",
       ["Felixstowe South Container Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Felixstowe-Asia"]),
    _a("port_valencia", "Port of Valencia", 3, (-0.3, 39.4, (-0.1), 39.5), "seaport",
       ["Valencia Container Terminal", "Noatum Terminal"],
       parent_region="europe", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Valencia-Asia", "Valencia-Rotterdam"]),
    _a("port_genoa", "Port of Genoa", 3, (8.8, 44.4, 8.9, 44.5), "seaport",
       ["Genoa Container Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Genoa-Asia", "Genoa-Rotterdam"]),
    _a("port_barcelona", "Port of Barcelona", 3, (2.1, 41.3, 2.3, 41.4), "seaport",
       ["Barcelona Container Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Barcelona-Asia"]),
    _a("port_miami", "Port of Miami", 3, (-80.2, 25.7, (-80.1), 25.8), "seaport",
       ["PortMiami Container Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Miami-Caribbean", "Miami-Latin America"]),
    _a("port_houston", "Port of Houston", 3, (-95.0, 29.7, (-94.9), 29.8), "seaport",
       ["Barbours Cut Terminal", "Bayport Container Terminal"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Houston-Asia", "Houston-Latin America"]),
    _a("port_vancouver_bc", "Port of Vancouver (BC)", 3, (-123.1, 49.2, (-123.0), 49.4), "seaport",
       ["Vanterm Centerm", "Deltaport Terminal"],
       parent_region="north_america", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Vancouver-Asia", "Vancouver-Seattle"]),
    _a("port_halifax", "Port of Halifax", 3, (-63.6, 44.6, (-63.5), 44.7), "seaport",
       ["Halifax Container Terminal", "South End Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Halifax-Europe", "Halifax-Asia"]),
    _a("port_baltimore", "Port of Baltimore", 3, (-76.6, 39.2, (-76.5), 39.3), "seaport",
       ["Seagirt Marine Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Baltimore-Europe"]),
    _a("port_charleston", "Port of Charleston", 3, (-79.9, 32.8, (-79.8), 32.9), "seaport",
       ["Wando Welch Terminal", "Hugh K. Leatherman Terminal"],
       parent_region="cluster_savannah", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Charleston-Rotterdam", "Charleston-Asia"]),
    _a("port_manila", "Port of Manila", 3, (120.9, 14.5, 121.0, 14.7), "seaport",
       ["Manila International Container Terminal"],
       parent_region="se_asia", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Manila-Shanghai", "Manila-LA"]),
    _a("port_bangkok", "Port of Laem Chabang (Bangkok)", 3, (100.8, 13.0, 101.0, 13.2), "seaport",
       ["Laem Chabang Container Terminal"],
       parent_region="se_asia", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Laem Chabang-Singapore", "Laem Chabang-Europe"]),
    _a("port_jakarta", "Port of Tanjung Priok (Jakarta)", 3, (106.8, -6.1, 107.0, -5.9), "seaport",
       ["Tanjung Priok Container Terminal"],
       parent_region="se_asia", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Jakarta-Singapore", "Jakarta-Rotterdam"]),
    _a("port_chennai", "Port of Chennai", 3, (80.2, 13.0, 80.4, 13.2), "seaport",
       ["Chennai Container Terminal"],
       parent_region="cluster_mumbai", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Chennai-Singapore", "Chennai-Europe"]),
    _a("port_mundra", "Port of Mundra", 3, (69.6, 22.7, 69.8, 22.9), "seaport",
       ["Mundra Container Terminal", "Adani Mundra Port"],
       parent_region="cluster_mumbai", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Mundra-Dubai", "Mundra-Europe"]),
    _a("port_karachi", "Port of Karachi", 3, (66.9, 24.8, 67.0, 24.9), "seaport",
       ["Karachi International Container Terminal"],
       parent_region="south_asia", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Karachi-Dubai", "Karachi-Europe"]),
    _a("port_dar_es_salaam", "Port of Dar es Salaam", 3, (39.2, -6.8, 39.3, -6.7), "seaport",
       ["Dar es Salaam Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Dar es Salaam-Dubai"]),
    _a("port_abidjan", "Port of Abidjan", 3, (-3.9, 5.3, (-3.8), 5.4), "seaport",
       ["Abidjan Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Abidjan-Rotterdam"]),
    _a("port_tema", "Port of Tema (Ghana)", 3, (-0.0, 5.6, 0.1, 5.7), "seaport",
       ["Tema Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Tema-Rotterdam"]),
    _a("port_douala", "Port of Douala", 3, (9.7, 4.0, 9.8, 4.1), "seaport",
       ["Douala Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Douala-Europe"]),
    _a("port_buenos_aires", "Port of Buenos Aires", 3, (-58.4, -34.6, (-58.3), -34.5), "seaport",
       ["Buenos Aires Container Terminal"],
       parent_region="latin_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Buenos Aires-Rotterdam", "Buenos Aires-Shanghai"]),
    _a("port_rio", "Port of Rio de Janeiro", 3, (-43.2, -23.0, (-43.1), -22.9), "seaport",
       ["Rio de Janeiro Container Terminal"],
       parent_region="latin_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Rio-Rotterdam"]),
    _a("port_guayaquil", "Port of Guayaquil", 3, (-79.9, -2.2, (-79.8), -2.1), "seaport",
       ["Guayaquil Container Terminal"],
       parent_region="latin_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Guayaquil-LA", "Guayaquil-Asia"]),
    _a("port_copenhagen_malmo", "Port of Copenhagen-Malmo", 3, (12.6, 55.6, 12.7, 55.7), "seaport",
       ["Copenhagen Malmo Port"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Copenhagen-Rotterdam"]),
    _a("port_gothenburg", "Port of Gothenburg", 3, (11.9, 57.7, 12.0, 57.8), "seaport",
       ["Gothenburg Container Terminal", "Arendal Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_helsinki", "Port of Helsinki", 3, (24.8, 60.1, 25.1, 60.2), "seaport",
       ["Helsinki West Harbour Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_odessa", "Port of Odesa", 3, (30.7, 46.4, 30.8, 46.5), "seaport",
       ["Odesa Port Terminal"],
       parent_region="europe", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Odesa-Istanbul"]),
    _a("port_suez_canal_zone", "Suez Canal Container Terminal", 3, (32.3, 29.9, 32.5, 30.1), "seaport",
       ["SCZone Container Terminal", "East Port Said Terminal"],
       parent_region="choke_suez", poll_interval_seconds=180, confidence_threshold=0.75,
       trade_lanes=["Suez-Asia", "Suez-Europe"]),
    _a("port_salalah", "Port of Salalah", 3, (54.0, 16.9, 54.1, 17.1), "seaport",
       ["Salalah Container Terminal"],
       parent_region="choke_bab_el_mandeb", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Salalah-Asia", "Salalah-Europe"]),
    _a("port_colon", "Port of Colon (Panama)", 3, (-79.9, 9.3, (-79.8), 9.4), "seaport",
       ["Colon Container Terminal", "Manzanillo International Terminal"],
       parent_region="choke_panama", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Colon-LA", "Colon-NY"]),
    _a("port_nagoya", "Port of Nagoya", 3, (136.8, 35.0, 137.0, 35.2), "seaport",
       ["Nagoya Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Nagoya-LA", "Nagoya-SE Asia"]),
    _a("port_kobe", "Port of Kobe", 3, (135.1, 34.6, 135.2, 34.7), "seaport",
       ["Kobe Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_yokohama", "Port of Yokohama", 3, (139.6, 35.4, 139.7, 35.5), "seaport",
       ["Yokohama Container Terminal", "Minami Honmoku Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Yokohama-LA", "Yokohama-SE Asia"]),
    _a("port_vladivostok", "Port of Vladivostok", 3, (131.7, 43.0, 131.9, 43.2), "seaport",
       ["Vladivostok Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Vladivostok-Asia"]),
    _a("port_dalian", "Port of Dalian", 3, (121.6, 38.8, 121.8, 39.0), "seaport",
       ["Dalian Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Dalian-SE Asia"]),
    _a("port_muscat", "Port of Sultan Qaboos (Muscat)", 3, (58.5, 23.6, 58.7, 23.7), "seaport",
       ["Sultan Qaboos Container Terminal"],
       parent_region="choke_hormuz", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_dakar", "Port of Dakar", 3, (-17.5, 14.6, (-17.4), 14.7), "seaport",
       ["Dakar Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_mombasa_inner", "Mombasa Inner Harbour", 3, (39.6, -4.0, 39.8, -3.9), "seaport",
       ["Mombasa Old Port", "Mombasa Container Terminal"],
       parent_region="cluster_mombasa", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_taipei", "Port of Taipei", 3, (121.4, 25.1, 121.5, 25.2), "seaport",
       ["Taipei Port Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_columbo_inner", "Colombo South Harbour", 3, (79.8, 6.9, 79.9, 7.0), "seaport",
       ["Colombo South Container Terminal"],
       parent_region="cluster_colombo", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_chittagong", "Port of Chittagong", 3, (91.8, 22.2, 91.9, 22.3), "seaport",
       ["Chittagong Container Terminal"],
       parent_region="south_asia", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_ashdod", "Port of Ashdod", 3, (34.6, 31.7, 34.7, 31.8), "seaport",
       ["Ashdod Container Terminal"],
       parent_region="gulf_suez", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_haifa", "Port of Haifa", 3, (34.8, 32.7, 34.9, 32.8), "seaport",
       ["Haifa Container Terminal"],
       parent_region="gulf_suez", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("port_kobe_osaka", "Port of Kobe-Osaka", 3, (135.1, 34.6, 135.4, 34.8), "seaport",
       ["Kobe-Osaka Container Terminal"],
       parent_region="china_ea", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Kobe-SE Asia", "Kobe-LA"]),
    _a("port_casablanca", "Port of Casablanca", 3, (-7.6, 33.5, (-7.5), 33.6), "seaport",
       ["Casablanca Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Casablanca-Marseille", "Casablanca-Barcelona"]),
    _a("port_tunis", "Port of Tunis (Rades)", 3, (10.2, 36.7, 10.3, 36.8), "seaport",
       ["Rades Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Tunis-Marseille", "Tunis-Genoa"]),
    _a("port_tripoli_libya", "Port of Tripoli (Libya)", 3, (13.1, 32.8, 13.2, 32.9), "seaport",
       ["Tripoli Container Terminal"],
       parent_region="africa", poll_interval_seconds=360, confidence_threshold=0.90),
    _a("port_maputo", "Port of Maputo", 3, (32.5, -25.9, 32.7, -25.8), "seaport",
       ["Maputo Container Terminal"],
       parent_region="africa", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Maputo-Durban", "Maputo-Singapore"]),
    _a("port_alexandria", "Port of Alexandria", 3, (29.8, 31.1, 29.9, 31.2), "seaport",
       ["Alexandria Container Terminal"],
       parent_region="gulf_suez", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Alexandria-Europe", "Alexandria-Suez"]),
    _a("port_mumbai_jnpt", "JNPT Mumbai (Nhava Sheva)", 3, (72.9, 18.9, 73.0, 19.0), "seaport",
       ["JNPT Container Terminal", "NSICT Terminal"],
       parent_region="cluster_mumbai", poll_interval_seconds=180, confidence_threshold=0.80,
       trade_lanes=["Mumbai-Singapore", "Mumbai-Europe"]),
    _a("port_kolkata", "Port of Kolkata (Haldia)", 3, (88.1, 22.5, 88.3, 22.7), "seaport",
       ["Haldia Container Terminal"],
       parent_region="cluster_mumbai", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Kolkata-Singapore"]),
    _a("port_acajutla", "Port of Acajutla (El Salvador)", 3, (-89.8, 13.5, (-89.7), 13.6), "seaport",
       ["Acajutla Container Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85,
       trade_lanes=["Acajutla-LA"]),
    _a("air_atlanta", "Atlanta Air Cargo Hub", 3, (-84.4, 33.6, (-84.3), 33.7), "airport",
       ["Hartsfield-Jackson Atlanta Cargo"],
       parent_region="hub_memphis", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("air_miami_cargo", "Miami International Cargo", 3, (-80.3, 25.8, (-80.2), 25.9), "airport",
       ["Miami Cargo Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("air_sfo_cargo", "San Francisco International Cargo", 3, (-122.4, 37.6, (-122.3), 37.7), "airport",
       ["SFO Cargo Terminal"],
       parent_region="north_america", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("air_doha", "Hamad International Cargo (Doha)", 3, (51.6, 25.2, 51.7, 25.3), "airport",
       ["Doha Cargo Hub"],
       parent_region="choke_hormuz", poll_interval_seconds=180, confidence_threshold=0.80),
    _a("air_bangkok_cargo", "Suvarnabhumi Cargo (Bangkok)", 3, (100.7, 13.6, 100.8, 13.7), "airport",
       ["Suvarnabhumi Cargo Terminal"],
       parent_region="se_asia", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("rail_hannover", "Hannover Intermodal Hub", 3, (9.7, 52.3, 9.8, 52.4), "rail_hub",
       ["Hannover Intermodal Terminal"],
       parent_region="cluster_rotterdam", poll_interval_seconds=300, confidence_threshold=0.85),
    _a("dry_port_dryport_kolkata", "ICD Kolkata", 3, (88.3, 22.5, 88.4, 22.6), "dry_port",
       ["Kolkata ICD"],
       parent_region="cluster_mumbai", poll_interval_seconds=300, confidence_threshold=0.85),
]

AGENT_REGISTRY: dict[str, dict[str, Any]] = {}

for _region_list in [TIER_1_REGIONS, TIER_2_REGIONS, TIER_3_REGIONS]:
    for _entry in _region_list:
        AGENT_REGISTRY[_entry["region_id"]] = _entry

TIER_HIERARCHY: dict[int, dict[str, Any]] = {
    1: {
        "name": "Regional Agents",
        "description": "Major geographic regions covering global trade corridors",
        "regions": [e for e in TIER_1_REGIONS],
        "count": len(TIER_1_REGIONS),
    },
    2: {
        "name": "Port Clusters & Chokepoints",
        "description": "Major port clusters, chokepoints, air hubs, and rail corridors",
        "regions": [e for e in TIER_2_REGIONS],
        "count": len(TIER_2_REGIONS),
    },
    3: {
        "name": "Individual Ports & Hubs",
        "description": "Individual seaports, airports, and logistics nodes",
        "regions": [e for e in TIER_3_REGIONS],
        "count": len(TIER_3_REGIONS),
    },
}

TOTAL_AGENT_COUNT: int = len(AGENT_REGISTRY)